name: Join Split Files and Deploy

on:
  push:
    branches:
      - master

jobs:
  join_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y zip

      - name: Join split files
        run: |
          cat app.bundle.js.part.* > app.bundle.js


